# Generated by Django 4.0 on 2022-01-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='Urls',
        ),
    ]
