# Generated by Django 4.0 on 2022-02-10 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_url_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='name',
        ),
        migrations.AddField(
            model_name='urls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urls',
            name='long_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
